# Generated by Django 6.0.5 on 2026-05-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(1, 'Freio'), (2, 'Transmissão'), (3, 'Suspensão'), (4, 'Rodas'), (5, 'Direção (Guidão/Mesa/Caixa)'), (6, 'Selim e Canote'), (7, 'Quadro')])),
                ('kilometers', models.FloatField(default=0.0, help_text='Quilometragem acumulada no componente')),
                ('install_date', models.DateField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bikes.bike')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('kilometers_at_service', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintence_records', to='bikes.component')),
            ],
        ),
    ]
