# Generated by Django 6.0.5 on 2026-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenceRecord',
            new_name='MaintenanceRecord',
        ),
        migrations.AddField(
            model_name='component',
            name='max_kilometers',
            field=models.FloatField(default=2000.0),
        ),
    ]
