# Generated by Django 6.0.5 on 2026-05-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_rename_maintencerecord_maintenancerecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='max_kilometers',
            field=models.FloatField(default=2000.0, help_text='Quilometragem máxima para manutenção'),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('distance', models.FloatField(help_text='Distância em KM')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='bikes.bike')),
            ],
        ),
    ]
